### ISSUE TITLE
Running scriptlet: NetworkManager-1:1.32.10-4.el8.x86_64

### ISSUE THREAD

**Issue by Bill-ColeUS** [AlmaLinux/almalinux-deploy#102]
Hello!

I've started migrating various servers (web & email) from CentOS 8 to AlmaLinux 8. Your great script is just awesome and so far everything has migrated without any problems.

But... for one server the migration showed an error, that hasn't appeared anywhere else, the relevant part is:

```
  Upgrading        : NetworkManager-1:1.32.10-4.el8.x86_64              370/973 
warning: /etc/NetworkManager/NetworkManager.conf created as /etc/NetworkManager/NetworkManager.conf.rpmnew

  Running scriptlet: NetworkManager-1:1.32.10-4.el8.x86_64              370/973 
/usr/bin/udevadm: symbol lookup error: /usr/bin/udevadm: undefined symbol: ifname_valid, version SD_SHARED
/usr/bin/udevadm: symbol lookup error: /usr/bin/udevadm: undefined symbol: ifname_valid, version SD_SHARED
```

The migration finished and I rebooted the server. While everything appears normal, I wanted to document the error here in case its relevant to anyone else.

Thank you.

**Comment by Ovat1975** [comment]
it look like ifname_valid is a symbol from an internal library that's been renamed
and  *new* udevadm uses the new name

**Comment by Bill-ColeUS** [comment]
No interest... closing.

**Comment by andrewlukoshko** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2012123
