### ISSUE TITLE
AlmaLinux 8.5 problems building rpms on OBS

### ISSUE THREAD

**Issue by jlbprof** [AlmaLinux/almalinux-deploy#103]
When you released AlmaLinux 8.5, all the OBS packages that we build using Alma failed with this issue:

[   12s] /usr/bin/rpmdb: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory

This has been noted on the OBS mailing list.  But no viable solution has been presented, someone suggested doing this:

``` So, now "Preinstall: sqlite-libs" is needed.```

But that did not work for us and broke other CentOS builds for us.

I was hoping you could help us get past this issue.

**Comment by andrewlukoshko** [comment]
Hi. Is the error still occur?
