### ISSUE TITLE
Alma 8.5 has old nmap version 7.70 in repository

### ISSUE THREAD

**Issue by tomsuzans** [AlmaLinux/almalinux-deploy#118]
Alma 8.5 has old nmap version 7.70 in repository. The latest version is 7.92-1 that supports some new features wery needed.

**Comment by andrewlukoshko** [comment]
Hi.
AlmaLinux 8.5 has the same nmap version as RHEL 8.5 because we're 1:1.
If you need newer version you should consider building it from source or from Fedora src.rpm.
