### ISSUE TITLE
almalinux-deploy within Virtuozzo Containers

### ISSUE THREAD

**Issue by futureweb** [AlmaLinux/almalinux-deploy#119]
Hi there,
we are evaluating to migrate our Centos 8 containers virtualized under Virtuozzo Hybrid Server 7 to AlmaLinux.
I just wanted to ask if anyone here has any experience with the almalinux-deploy script within containers.
Does this work without problems?
Is there anything to consider?
Thank you, best regards from Austria
Andy

**Comment by jonathanspw** [comment]
It works just fine within Virtuozzo/OpenVZ 7 containers.  It will not work on OpenVZ 6 or anything on 2.6.32.x kernel.

**Comment by futureweb** [comment]
> It works just fine within Virtuozzo/OpenVZ 7 containers. It will not work on OpenVZ 6 or anything on 2.6.32.x kernel.

Thx for confirmation. Will start some Tests next week then! :-)

**Comment by futureweb** [comment]
@jonathanspw - I have another question that you might be able to help me with.
There is a migration script for VZLinux to upgrade from Centos 7 to VZLinux 8. (https://docs.virtuozzo.com/virtuozzo_hybrid_server_7_users_guide/advanced-tasks/converting-centos-in-ves-to-vzlinux8.html)
Do you also plan to implement a migration path from Centos 7 to AlmaLinux 8? (best with compatibility to Plesk)
Thank you, best regards from Tyrol
Andy

**Comment by jaboutboul** [comment]
Check out https://almalinux.org/elevate

**Comment by futureweb** [comment]
Thank you for pointing out the ELevate Project ... some more information if someone stumbles over this post --> it seems like Plesk + ELevate Team is looking into making Centos 7 -> AlmaLinux 8 + Plesk a supported upgrade Path --> https://talk.plesk.com/threads/elevate-migrate-centos-7-to-almalinux-8.362661/
