### ISSUE TITLE
Server is stuck at grub installation

### ISSUE THREAD

**Issue by nidhin215** [AlmaLinux/almalinux-deploy#124]
Hi,

The conversion script is getting stuck here. I'm running this on a  4×960 GB SSD SATA, hard raid

  Running scriptlet: nss-3.67.0-7.el8_5.x86_64                          960/960 
  Running scriptlet: grub2-efi-x64-1:2.02-106.el8.alma.x86_64           960/960
   client_loop: send disconnect: Broken pipe

Can anyone provide an insight?

**Comment by andrewlukoshko** [comment]
Hello. I don't think it's related to grub update.  Looks like connection loss.
