### ISSUE TITLE
Would it will auto install x-window? 

### ISSUE THREAD

**Issue by Athxx** [AlmaLinux/almalinux-deploy#125]
I want to change my server (only command) to AlmaLinux from centos8 stream, is it will auto install x-window? I don't want to install x-window

**Comment by andrewlukoshko** [comment]
If you don't have X now then it won't be installed.
However I'm not sure you'll be able to migrate from CentOS Stream 8 because it has newer packages than AlmaLinux 8 so basically you'll have to downgrade. But feel free to try it (maybe script modifications will be required) and share you results.
