### ISSUE TITLE
can not update

### ISSUE THREAD

**Issue by ahmedawais** [AlmaLinux/almalinux-deploy#126]
tried 
dnf update 
dnf clean packages
dnf clean all
dnf update 

Transaction check is executed
Transaction check was successful.
Transaction is being tested
The downloaded packages have been cached until the next successful transaction.
You can remove cached packages using the "dnf clean packages" command.
Error: Transaction test failed:
  File /usr/share/pixmaps/poweredby.png from the installation of almalinux-logos-httpd-84.5-1.el8.noarch collides with the file from the package centos-logos-httpd-80.5-2.el8.noarch

can not remove centos-logos-httpd-80.5-2.el8.noarch because it contains crucial packages php apr-util etc

**Comment by andrewlukoshko** [comment]
That sounds strange because centos-logos-httpd should be deleted automatically before migration.
Please show the full log.
