### ISSUE TITLE
Different repo-file-names

### ISSUE THREAD

**Issue by nuxodin** [AlmaLinux/almalinux-deploy#127]
In my case, the repo files are called as follows, what should I do?

> CentOS-Base.repo
> CentOS-centosplus.repo
> CentOS-CR.repo
> CentOS-Debuginfo.repo
> CentOS-Devel.repo
> CentOS-Extras.repo
> CentOS-fasttrack.repo
> CentOS-HA.repo
> CentOS-Media.repo
> CentOS-PowerTools.repo
> CentOS-Sources.repo
> CentOS-Vault.repo

**Comment by whorped** [comment]
What version of Cent 8 are you running? Those are the older repo filenames (from centos-repos RPM) before they changed the package name to centos-linux-repos. Makes me think you are at an older version like 8.2 or 8.3 which isn't supported by the conversion script (minimum supported version if 8.4).

**Comment by nuxodin** [comment]
I run CentOS 8.2.2004

Hopefully it can also be updated...?

**Comment by nuxodin** [comment]
Or can you do the migration for a fee?

**Comment by whorped** [comment]
my suggestion would be:

1. backup system if not already
2. point your repo files at the vault cent8 repos. the original repos are no longer available. from https://github.com/AlmaLinux/almalinux-deploy/issues/120 discussion:

```
find /etc/yum.repos.d -type f -exec sed -i 's/mirrorlist=http:\/\/mirrorlist.centos.org/\#mirrorlist=http:\/\/mirrorlist.centos.org/g' {} \;
find /etc/yum.repos.d -type f -exec sed -i 's/\#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/vault.centos.org/g' {} \;
dnf update -y
reboot
```
3. if above update to centos 8.5 is successful (check /etc/redhat-release) you should then be able to run the almalinux-deploy.sh migration script.

**Comment by nuxodin** [comment]
Thanks for your answer.
Unfortunately, that didn't help, I get:

```
[root@s3 yum.repos.d]# find /etc/yum.repos.d -type f -exec sed -i 's/mirrorlist=http:\/\/mirrorlist.centos.org/\#mirrorlist=http:\/\/mirrorlist.centos.org/g' {} \;
[root@s3 yum.repos.d]# find /etc/yum.repos.d -type f -exec sed -i 's/\#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/vault.centos.org/g' {} \;
[root@s3 yum.repos.d]# dnf update -y
CentOS-8 - AppStream                                                                                                                                                                                                                             37 kB/s | 282  B     00:00
Errors during downloading metadata for repository 'AppStream':
  - Status code: 404 for http://asi-fs-n.contabo.net/centos/8/AppStream/x86_64/os/repodata/repomd.xml (IP: 79.143.183.106)
Error: Failed to download metadata for repo 'AppStream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

```

**Comment by andrewlukoshko** [comment]
please show your repo files content. Is it modified?
I'm wondering where asi-fs-n.contabo.net came from.

**Comment by nuxodin** [comment]
This is the content of "CentOS-Base.repo"  
asi-fs-n.contabo.net seams to be a morror from my vps provider...?
![grafik](https://user-images.githubusercontent.com/16326/165063529-2c77688e-d287-4bfc-9323-a9ac2de6e819.png)

**Comment by andrewlukoshko** [comment]
Support for older CentOS releases was introduced by https://github.com/AlmaLinux/almalinux-deploy/pull/140
