### ISSUE TITLE
Mirror List down

### ISSUE THREAD

**Issue by bluegeeks1988** [AlmaLinux/almalinux-deploy#131]
Hi, have updated all the mirrors with sed, but it looks like they are all down :(

As i keep getting: 

[root@stoic-dewdney ~]# bash almalinux-deploy.sh -f
CentOS Linux 8 - Extras                          24 kB/s | 1.5 kB     00:00
CentOS Linux 8 - PowerTools                     944  B/s | 168  B     00:00
Errors during downloading metadata for repository 'powertools':
  - Status code: 404 for http://mirror.eu.oneandone.net/linux/distributions/cent  os/8/PowerTools/x86_64/os/repodata/repomd.xml (IP: 217.72.206.21)
Error: Failed to download metadata for repo 'powertools': Cannot download repomd  .xml: Cannot download repodata/repomd.xml: All mirrors were tried
Fix DNF repositories to live mirror and run dnf upgrade -y. Exit code: 1ERROR

Are you able to repair this please.

Thanks
Aaron

**Comment by andrewlukoshko** [comment]
This issue was related to particular mirror, not mirrorlist.
