### ISSUE TITLE
Rocky to Alma - Cockpit Logo

### ISSUE THREAD

**Issue by fz72** [AlmaLinux/almalinux-deploy#132]
Hi,
after running the script I rebooted and started cockpit. In the web interface there are still Rocky Linux Logos present.
This is caused by file /usr/share/pixmaps/cockpit.png from package cockpit (Tested with renaming).
sudo dnf remove cockpit
and
sudo dnf install cockpit
has worked for me.

**Comment by srbala** [comment]
May need to add `cockpit` package to branding list to remove?

**Comment by srbala** [comment]
@fz72 Installed Rocky linux and converted to Almalinux. Package `cockpit` package install looks good, screen capture below. The `cockpit.png` is default stock image, not a Rocky logo.

![image](https://user-images.githubusercontent.com/1273137/168909679-e3d3d5f3-8c9b-4f0d-bad0-67e12be77c4d.png)

**Comment by fz72** [comment]
@srbala thank you for testing. It was a remote server so i have not checked the image. I only renamed the file. Maybe only a webserver cache problem? So you can close the issue?
