### ISSUE TITLE
Unable to log in to cloud init image 

### ISSUE THREAD

**Issue by RobertFloor** [AlmaLinux/almalinux-deploy#134]
Hi there

I was following the guide here https://wiki.almalinux.org/cloud/Generic-cloud-on-local.html#create-a-snapshot-from-the-image but was unable to set a username password or ssh key that let me log in. It tries several options but tey did not work 

It kept saying Login incorrect

I followed this guide for centos: https://wiki.almalinux.org/cloud/Generic-cloud-on-local.html#create-a-snapshot-from-the-image or for RHEL (very similar to the Approach in the Alma Linux wiki) https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_and_managing_cloud-init_for_rhel_8/index

 and it works for these distros.
So my question is, has anybody successfully used the guide in the wiki guide to get a cloud-init image for alma Linux and how had he or she set the password and user. ? What is the username-password combo for the wiki example? 

Thanks for your help
Kind regards,
Robert

**Comment by LKHN** [comment]
Hey @RobertFloor :wave: 
It's the wrong please for this issue. Could you recreate it on the [ AlmaLinux OS Cloud Images](https://github.com/AlmaLinux/cloud-images) project?

Thanks!
