### ISSUE TITLE
curl error 6 from centos 8.5 to alma 8.5

### ISSUE THREAD

**Issue by carlo9999999** [AlmaLinux/almalinux-deploy#135]
hello i have a full update centos 8.5 but i have this error

[root@lnx2020 ~]# ./almalinux-deploy.sh 
Check root privileges                                                 OK
Download RPM-GPG-KEY-AlmaLinux                                        ERROR
    curl: (60) SSL certificate problem: self signed certificate in certificate chain
    More details here: https://curl.haxx.se/docs/sslcerts.html
    
    curl failed to verify the legitimacy of the server and therefore could not
    establish a secure connection to it. To learn more about this situation and
    how to fix it, please visit the web page mentioned above.
[root@lnx-asmn2020 ~]# cat /etc/redhat-release 
CentOS Linux release 8.5.2111
[root@lnx2020 ~]#

**Comment by andrewlukoshko** [comment]
Hi.
Is error still occur?
