### ISSUE TITLE
Sysctl

### ISSUE THREAD

**Issue by alexfabio** [AlmaLinux/almalinux-deploy#159]
Hello guys
I've been trying configure some system params ( _net.core.rmem_max_ and _net.core.wmem_max_) but not suceeded.

I added these lines below to the file **_/etc/sysctl.conf_**

**net.core.rmem_max = 26214400
net.core.wmem_max = 1048576**

and then I execute **_sysctl -p_**  but this outputs these errors:

**sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory
sysctl: cannot stat /proc/sys/net/core/wmem_max: No such file or directory**

I tried directaly with 
**sysctl -w net.core.rmem_max=26214400**
but still the same error:
**sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory**

Any help is appreciated.
Thanks.

**Comment by andrewlukoshko** [comment]
I can't reproduce this on both AlmaLinux 8 and 9.
```
$ cat /proc/sys/net/core/rmem_max
134217728
$ cat  /proc/sys/net/core/wmem_max
134217728
```
What AlmaLinux and kernel version used?

**Comment by alexfabio** [comment]
Operating System: AlmaLinux 8.7 (Stone Smilodon)
Kernel: Linux 3.10.0-1160.53.1.vz7.185.3

**Comment by andrewlukoshko** [comment]
Linux 3.10.0-1160.53.1.vz7.185.3 is not AlmaLinux kernel
