### ISSUE TITLE
RHEL 9.1 to AlmaLinux 9.1 doesn't work well despite no error

### ISSUE THREAD

**Issue by mightyspiky** [AlmaLinux/almalinux-deploy#160]
I've already converted some Oracle Linux 8 LXC containers to AlmaLinux 8 with almalinux-deploy script and it seems to work very well, among others all package are reinstalled with their AlmaLinux version.

Now, after that I tried to convert a RHEL 9.1 kvm virtual machine and it didn't go as well. First thing I saw was that only a minimal set of packages were reinstalled and I also get this after migration:

[root@vm ~]# dnf list installed
Failed loading plugin "product-id": No module named 'gi.repository'
Failed loading plugin "subscription-manager": No module named 'gi.repository'
Failed loading plugin "upload-profile": No module named 'gi.repository'
...

[root@vm ~]# subscription-manager 
Unable to find Subscription Manager module.
Error: No module named 'gi.repository'
[root@vm ~]#

The errors with "dnf" command don't seem very clean and "subscription-manager" command should not even be still available since it's RHEL-only stuff right?

Here's what I got at the end of migration:

Complete!
All Secure Boot related packages which were not released by AlmaLinux are reinstalledOK

Migration to AlmaLinux is completed

**Comment by pixdrift** [comment]
I just ran the migration tool on a clean RHEL 9.2 and the process was all pretty smooth except for the above plugin errors. 

These plugins are related to `subscription-manager` (subscribed to RHN), and removing `subscription-manager` removed the failed plugin warnings for me.

I guess the point of me posting is, should the script be removing the `subscription-manager` package as part of the process? Not sure what utility it has in an Alma install?

A summary of what is removed when the `subscription-manager` package was removed

```
======================================================================================================================
 Package                                  Arch     Version                     Repository                        Size
======================================================================================================================
Removing:
 subscription-manager                     x86_64   1.29.33.1-1.el9_2.alma      @baseos                          3.2 M
Removing unused dependencies:
 dmidecode                                x86_64   1:3.3-7.el9                 @rhel-9-for-x86_64-baseos-rpms   226 k
 libdnf-plugin-subscription-manager       x86_64   1.29.33.1-1.el9_2.alma      @baseos                           63 k
 python3-cloud-what                       x86_64   1.29.33.1-1.el9_2.alma      @baseos                           76 k
 python3-decorator                        noarch   4.4.2-6.el9                 @rhel-9-for-x86_64-baseos-rpms    61 k
 python3-ethtool                          x86_64   0.15-2.el9                  @rhel-9-for-x86_64-baseos-rpms    94 k
 python3-iniparse                         noarch   0.4-45.el9                  @rhel-9-for-x86_64-baseos-rpms   106 k
 python3-inotify                          noarch   0.9.6-25.el9                @rhel-9-for-x86_64-baseos-rpms   244 k
 python3-librepo                          x86_64   1.14.5-1.el9                @rhel-9-for-x86_64-baseos-rpms   183 k
 python3-subscription-manager-rhsm        x86_64   1.29.33.1-1.el9_2.alma      @baseos                          449 k
 subscription-manager-rhsm-certificates   noarch   20220623-1.el9              @rhel-9-for-x86_64-baseos-rpms    27 k
 usermode                                 x86_64   1.114-4.el9                 @rhel-9-for-x86_64-baseos-rpms   836 k
 virt-what                                x86_64   1.25-3.el9                  @rhel-9-for-x86_64-baseos-rpms    56 k

Transaction Summary
======================================================================================================================
```

DNF errors gone after removal of `subscription-manager` package that removes the plugin references from DNF config.
```
# dnf update
Last metadata expiration check: 0:15:01 ago on Tue 16 May 2023 12:22:50.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by m10k** [comment]
I ran into the same issue when I migrated a RHEL9.2 installation. I'm not sure if there are valid reasons to keep subscription-manager installed, but I figured that automatically uninstalling it may be too intrusive for some people, so I submitted a PR that addresses this issue by disabling all RedHat-specific dnf plugins (#167).

**Comment by pixdrift** [comment]
Nice clean solution @m10k 👍
