### ISSUE TITLE
"leapp update" failed on python problem after final package downloading

### ISSUE THREAD

**Issue by Xingeqwd** [AlmaLinux/almalinux-deploy#161]
**Foreword**
Hello there, i got some problem here. and think i need help...
After sloving nearing ten problems, it's finally almost reach the end, but here comes a another problem here i cant handle
</br>
**Condition overview**
When i processing the “leapp upgrade” on my Centos7.9
(roughly in accordance with [this guidance of almaLinux](https://wiki.almalinux.org/elevate/ELevate-quickstart-guide.html) to transfrom my system to almalinux),
It always return error like this(seems like a python functioning programical problem?_like picture showned below)
![image](https://user-images.githubusercontent.com/46107662/214871412-6047ab4c-d1a9-4b7d-973f-6896730c155a.png)
text is like:

```

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Process Process-473:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute
```

That's so strange, right? Normally, this shouldn't have this kind of problem.......
</br>
**Tried of solution**
(Similar problems have occurred before, but it should be a problem with my local python, and it will be solved after reinstalling)
like [this github link](https://github.com/certbot/certbot/issues/7645) showned. (Actually speaking, that is the first question spqwned, six or seven before now...)
But on this time, these method(and similar) seems useless

BTW, another master on [chat.almalinux.org](https://chat.almalinux.org) told me to try the evaluation version scriept, but it didn't work, the error condition persists
</br>
**Files**
i thought these haven't sensitive content in it, for the sake of convenience, I put it up
[leapp-report.txt](https://github.com/oamg/leapp-repository/files/10510659/leapp-report.txt)
[leapp-upgrade.log](https://github.com/oamg/leapp-repository/files/10510668/leapp-upgrade.log)
</br>
**Others**
Could someone help me please? Or any ideas are welcome!
Thanks a lot to everyone for the generous help and patient reading!
Wish you have a good good day.

**Comment by Xingeqwd** [comment]
In fact, I also posted a post on "leapp-repository", and the boss there told me that this is a problem unique to almalinux scripts,

It seems to me that this is indeed the case. The problem lies in the 218 of your script [GitHub link to dnfplugin.py#218]("https://github.com/oamg/leapp-repository/blob/cdbbb83e0a52d4e6a84281dad19a7520ce1115b7/repos/system_upgrade/common/libraries/dnfplugin.py#L218")

As the master said there  [a link to the comment]("https://github.com/oamg/leapp-repository/issues/1016#issuecomment-1405227891") I can only seek here for help

**Comment by Xingeqwd** [comment]
Additional speaking, by the way, after asking questions to leeapp-repository to no avail, I also tried to post on [almalinux.discourse.group](almalinux.discourse.group), 
but they are too strict with newcomers, and even blocked my account
![image](https://user-images.githubusercontent.com/46107662/215025863-467cf205-0a73-454a-bd03-157ecf03292e.png)
This really hit me 😥 
</br>
I hvae also sent these in that chat room [chat.almalinux.org](chat.almalinux.org)  but got no result 
(Actually, a master there asked me to try the evaluation version, but it didn't work_error condition persists), 
So I come here to seek for help


And, Finally, thanks to everyone! wish you have a good good day and life

**Comment by Xingeqwd** [comment]
Thanks to the master "Andrew Lukoshko" in the chat room [chat.almalinux](https://chat.almalinux.org) ", 
he help me to compile and launch an evaluation version of the script (6th), and this problem was solved.

In addition, there is another problem (as shown in the photo)
![image](https://user-images.githubusercontent.com/46107662/215148685-ca6ca6ef-3788-4592-b34e-6fc3127c93e5.png)
I'll try to solve it myself, if it doesn't work, come here and ask again.

**Comment by Xingeqwd** [comment]
Well, this problem has been solved (although a new problem has been created),

Please allow me to put the solution to this problem, it worked for me, hope it will be useful for others
(Actually, it’s just a recording of the speeches of a few bigwigs.
Could I post these? If I dont permitted to post it, I can delete it, please contact me)

**_Here is the solution to the problem of this post_**

> Andrew Lukoshko
> @xingeqwd please recheck your migration with latest RPMs from ELevate testing.
> package should be leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6
</br>

**_This is the solution to the first problem generated after this thread's problem was solved_**

> as the workflow offered by redhat
![image](https://user-images.githubusercontent.com/46107662/215155437-7dae6bbc-1fbe-4413-9bc6-2af82e70d877.png)
> i thought, this error should be happends on check 
![image (2)](https://user-images.githubusercontent.com/46107662/215155551-005a6fc2-edb9-4ee6-a1e6-e4260168a670.png)
> （It appears in early and after many checks）
> 
> rprilipskii
> Hello. That seems familiar to what I've encountered before.
> Does the /var/lib/leapp/el8userspace directory exist, can it be removed manually? If it's like what I encountered, it likely can't, due to being either mounted or opened by some process.
> 
> In fact, the most likely case is that it remained mounted from a previous upgrade run, where the target userspace was created, overlay FS got mounted, but the process halted later on and the dismount did not happen.

My system is centos7.9, trying to transfer to almalinux8, I hope it can help people later!

**Comment by Xingeqwd** [comment]
BTW, i create another post on [This GitHub link](https://github.com/AlmaLinux/almalinux-deploy/issues/162#issue-1560164083)

Cough Cough, if there are someone wonder for this? 
Please move on to watch

**Comment by MarcelNagy** [comment]
Hi Xingeqwd, I have the same problem. Can you help me solve this problem? Where can I find the leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6 package? I only found leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.1 on this page https://repo.almalinux.org/elevate/el7/x86_64/.
Could you please help me?
Thank you very much

**Comment by Xingeqwd** [comment]
> Hi Xingeqwd, I have the same problem. Can you help me solve this problem? Where can I find the leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6 package? I only found leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.1 on this page 
https://repo.almalinux.org/elevate/el7/x86_64/. Could you please help me? Thank you very much

hello @MarcelNagy!

Sure thing i can certainly help you. You only need to run "yum install leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6", men, that is such a simple way,

There are still sooooo many problem in future, man. And fortunately, I have approximately completed all of these.
You can visit more issue on my mainly page(by clicking on my avatar)

By The Way, you can also visit [this chat site](https://chat.almalinux.org/almalinux/channels/town-square) to asking more master. there are really much master there and they are all ghornally good guys.

Haha, glad to help you, let's Strike into the front!
And finally, wish you success!

**Comment by MarcelNagy** [comment]
Thanks, but when I run "yum install leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6" it says "No package leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6 available". I try your next advice. I will visit chat.almalinux.org.

**Comment by Xingeqwd** [comment]
> Thanks, but when I run "yum install leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6" it says "No package leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6 available". I try your next advice. I will visit chat.almalinux.org.
Hello

I thought this should be a spelling problem, but after checked i foud that it isn't

And otherwise, if you are moving from Centos to AlmaLinux, you should follow [this almalinux guidance](https://wiki.almalinux.org/elevate/ELevate-testing-guide.html), and running the `yum install leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6` before you running the `leapp (pre)upgrade`

So, I thought that you might missing some step above, this causing your yum didn't found this pack
You can do the previous one again, this should solve the problem.

**Comment by atefhares** [comment]
@Xingeqwd I have similar issues 
first I tried this solution https://stackoverflow.com/a/74034084/5993410 and it helped me solving the "can't set attribute" error. and also used testing elevate package leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6 by following this https://wiki.almalinux.org/elevate/ELevate-testing-guide.html

but it still fails with the following error.
if you understand the issue, could you plz help?

```
No matches found for the following disable plugin patterns: subscription-manager
552.3697741 upgrade[565]: Repository extras is listed more than once in the configuration
552.3650621 upgrade[565]: Warning: Package marked by Leapp to upgrade not found in repositories metadata: gpg-pubkey
552.3653101 upgrade[5651: Error unpacking rpm package python2-urilib3-1.24.2-3.module+el8.5.0+706+735ec463. noarch
552.3655671 upgrade[5651: Error: Transaction failed
```

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/14354272/218732191-255b676d-989a-4579-a758-287adbb8fddd.png">

**Comment by Xingeqwd** [comment]
> @Xingeqwd I have similar issues first I tried this solution https://stackoverflow.com/a/74034084/5993410 and it helped me solving the "can't set attribute" error. and also used testing elevate package leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.6 by following this https://wiki.almalinux.org/elevate/ELevate-testing-guide.html
> 
> but it still fails with the following error. if you understand the issue, could you plz help?
> 
> ```
> No matches found for the following disable plugin patterns: subscription-manager
> 552.3697741 upgrade[565]: Repository extras is listed more than once in the configuration
> 552.3650621 upgrade[565]: Warning: Package marked by Leapp to upgrade not found in repositories metadata: gpg-pubkey
> 552.3653101 upgrade[5651: Error unpacking rpm package python2-urilib3-1.24.2-3.module+el8.5.0+706+735ec463. noarch
> 552.3655671 upgrade[5651: Error: Transaction failed
> ```
> 
> <img alt="image" width="1728" src="https://user-images.githubusercontent.com/14354272/218732191-255b676d-989a-4579-a758-287adbb8fddd.png">

Hello @atefhares.
Sure, man, i will certainly help you!

If i were you, man, i will delete the subscription-manager first to make this problem easier
(because of we are centos, suscription have no use to us). 

And regarding the python-urllib, i thought that might be caused by a broken installation. you can easily try to reinstall the python2-urllib(eg. using the `yum reinstall python2-urllib`), if these dont work, try to reinstall python2*(using the `yum reinstall` **instread** of _remove/install_ !!!!! deleting all the python2 might causing a huge huge trouble)

I think this above should be effective(at least hope that)

ByTheWay, if i reply you late, you can also visit the Almalinux discussion room to ask the master there(they are really good guies). 
or you can also create a issue on "leapp" repository, there are also many good man there to help!

Hope these above work! wish you a good day and luck. 
Ready for the many many question in the front, these should be easily solved, strike them!
And feel free to ask me again, haha.

**Comment by atefhares** [comment]
@Xingeqwd Thanks a lot for your help. I am trying what you suggested and will also try to communicate with the team on MM. will update here again the status.
