### ISSUE TITLE
leapp update failed on the Actor of dnf_package_download

### ISSUE THREAD

**Issue by Xingeqwd** [AlmaLinux/almalinux-deploy#162]
### Foreword
Oh hoh, here comes another problem (after these dozen questions solved previous)......
But i think this should, really really be the last one. (this actor is nearing the end as the workflow).</br>

### Condition overview
When i processing the “leapp upgrade” on my Centos7.9
(roughly in accordance with [this guidance of almaLinux](https://wiki.almalinux.org/elevate/ELevate-quickstart-guide.html) to transfrom my system to almalinux),

**It will going a failure On the actor of :** 
> Actor: dnf_package_download
> Message: DNF execution failed with non zero exit code. 
> (detailed photo's below)

**_The error of leapp_**
![image](https://user-images.githubusercontent.com/46107662/215160876-669f890e-986a-46ef-afc3-e745c2aa0be7.png)
_Coding if needle_
```
============================================================
                       END OF ERRORS                        
============================================================
2023-01-28 01:19:14.440 ERROR    PID: 21447 leapp: 2023-01-28 01:19:13.239539 [ERROR] Actor: dnf_package_download
Message: DNF execution failed with non zero exit code.
STDOUT:
Last metadata expiration check: 0:02:05 ago on Sat Jan 28 01:13:08 2023.
Package python2-six-1.9.0-0.el7.noarch is already installed.
Dependencies resolved.
==============================================================================================================================================
 Package                                       Arch    Version                                                    Repository              Size
==============================================================================================================================================
Installing:
 adcli-doc                                     noarch  0.8.2-12.el8                                               almalinux8-baseos       61 k
 almalinux-indexhtml                           noarch  8-7.1.el8                                                  almalinux8-baseos      8.6 k
     replacing  centos-indexhtml.noarch 7-9.el7.centos
 almalinux-logos                               x86_64  84.5-1.el8                                                 almalinux8-appstream   362 k

```

**_The error of dnf_**
![image](https://user-images.githubusercontent.com/46107662/215158025-d0b753e3-9c75-464a-a92d-c78a9e678d39.png)
_Coding if needle_
```
(1955/1956): epel-release-8-10.el8.noarch.rpm   493 kB/s |  22 kB     00:00    
(1956/1956): zenity-3.28.1-2.el8.x86_64.rpm      16 MB/s | 4.0 MB     00:00    
--------------------------------------------------------------------------------
Total                                            31 MB/s | 2.0 GB     01:04     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
STDERR:
No matches found for the following disable plugin patterns: subscription-manager
Repository extras is listed more than once in the configuration
Repository extras-source is listed more than once in the configuration
Warning: Package marked by Leapp to install not found in repositories metadata: python3-nss ldns-utils ivy-local python3-javapackages
Warning: Package marked by Leapp to upgrade not found in repositories metadata: gpg-pubkey
RPM: warning: Generating 6 missing index(es), please wait...
Error: Transaction test error:
  file /usr/lib/python3.6/site-packages/__pycache__/six.cpython-36.opt-1.pyc from install of python3-six-1.11.0-8.el8.noarch conflicts with file from package python36-six-1.14.0-3.el7.noarch
  file /usr/lib/python3.6/site-packages/__pycache__/six.cpython-36.pyc from install of python3-six-1.11.0-8.el8.noarch conflicts with file from package python36-six-1.14.0-3.el7.noarch
  file /usr/lib/python3.6/site-packages/six.py from install of python3-six-1.11.0-8.el8.noarch conflicts with file from package python36-six-1.14.0-3.el7.noarch

```
 </br>

### Analyse and tried

It seems like the update script is trying to install gpg-pubkey python3-nss ldns-utils ivy-local python3-javapackages
However, these packages are not in the Centos repo (should be python36 instead of python3)
So the installation of the script was not successful
By The Way:
There is a issue very similar to mine "https://access.redhat.com/discussions/6259931#comment-2171591",
But his system is RHEL7 so he can directly running the "yum install" to solve. 
And my system is Centos7, I can't.</br>

### Afterword
Really, I really feel like this should be the last problem, the last one (this actor should be nearing the end), 
after these serveral days and dozen questions solved previous.

I will greatly greatly appreciating any help
Thanks a lot to everyone for the generous help and patient reading!
Wish you have a good good day and life.

**Comment by Xingeqwd** [comment]
I just figured it out!
 
As said in this article (the screenshot has been translated into English):
 
REHL7 kernel upgrades to REHL8 have this problem, because their package names conflict!(changed on REHL8)
This is indeed conflicts causing the problem. The details of my previous mistakes are all python36
 
——This is an article I referred to when I tried to upgrade from centos7 to 8 ("https://cloud-atlas.readthedocs.io/zh_CN/latest/linux/redhat_linux/centos/upgrade_centos_7_to_8.html"),
But in the end (because Centos LTS stopped maintenance and so on) gave up and went to almalinux


![image](https://user-images.githubusercontent.com/46107662/215183679-6c3dcfad-1166-431b-ac61-2e300cad6b86.png)

**Comment by Xingeqwd** [comment]
其实是我他妈的，一下子居然没想起来，连着干了太多天很累，人都懵了，他妈的，原来是这样啊
就他妈的，这点事情搞了一天，哎

也罢，希望这次顺利些吧（希望不要再给我空间不足报错了。。。。。。。。）

**Comment by Xingeqwd** [comment]
顺带一提，他妈的，又空间不足了好几次

太累了啊！就不翻译成英文了，哎，直接打中文吧，比较顺手。。。。。

**Comment by srbala** [comment]
@Xingeqwd Please keep the communication text in English.

If the issue is related to translation, we need both English and issue-related language text.

**Comment by Xingeqwd** [comment]
> @Xingeqwd Please keep the communication text in English.
> 
> If the issue is related to translation, we need both English and issue-related language text.

sorry sir, i will translate this to English
