### ISSUE TITLE
almalinux repo gpg keys not installed after centos stream 9 --> almalinux migration

### ISSUE THREAD

**Issue by jszarin** [AlmaLinux/almalinux-deploy#183]
After a successful centos stream 9 to almalinux migration, cockpit "Software Update" fails because the almalinux repos' keys are not installed.

`sudo dnf reinstall almalinux-repos` fixes the issue.

**Comment by yuravk** [comment]
The reason of the issue is `almalinux-gpg-keys` package isn’t installed during _CentOS Stream9 to AlmaLinux9 downgrade_
```
# rpm -qV almalinux-repos
Unsatisfied dependencies for almalinux-repos-9.3-1.el9.x86_64:
	almalinux-gpg-keys = 9.3-1.el9 is needed by (installed) almalinux-repos-9.3-1.el9.x86_64
```
