### ISSUE TITLE
BAD signature alma 8.8

### ISSUE THREAD

**Issue by msavchen** [AlmaLinux/almalinux-deploy#185]
Seems like the signature is wrong for Alma8.8 both x86_64 and aarch https://repo.almalinux.org/almalinux/8.8/cloud/aarch64/images/.
Getting `gpg: BAD signature from "AlmaLinux <packager@almalinux.org>" [unknown]`

**Comment by andrewlukoshko** [comment]
Thanks for this catch @msavchen 
Fixed
