### ISSUE TITLE
IP range blocked from Alma Linux?

### ISSUE THREAD

**Issue by theaustinayers** [AlmaLinux/almalinux-deploy#201]
Hey there guys!
We are leasing a block from IPXO that is 104.234.66.0/24 but whenever we connect our CloudLinux VM up to an IP in that range, it cannot ping whatsoever to the repo.almalinux.org (67.222.0.50).

From our main WAN:
`[Pinging repo.almalinux.org [67.222.0.50] with 32 bytes of data:
Reply from 67.222.0.50: bytes=32 time=34ms TTL=50
Reply from 67.222.0.50: bytes=32 time=34ms TTL=50

Ping statistics for 67.222.0.50:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
`

From the 104.234.66.0/24 block:
`[root@web home]# ping 67.222.0.50
PING 67.222.0.50 (67.222.0.50) 56(84) bytes of data.
^C
--- 67.222.0.50 ping statistics ---
46 packets transmitted, 0 received, 100% packet loss, time 46093ms
`

Can someone from AlmaLinux check to see if there's something happening with our IP range like maybe a previous blacklist?

**Comment by codyro** [comment]
Can you provide a trace to `67.222.0.50`? I'm able to reach your network from that machine.

```
[root@atl ~]# ping 104.234.66.1 -I enp1s0 -I 67.222.0.50
PING 104.234.66.1 (104.234.66.1) from 67.222.0.50 enp1s0: 56(84) bytes of data.
64 bytes from 104.234.66.1: icmp_seq=1 ttl=248 time=17.2 ms
64 bytes from 104.234.66.1: icmp_seq=2 ttl=248 time=16.7 ms
64 bytes from 104.234.66.1: icmp_seq=3 ttl=248 time=16.9 ms
64 bytes from 104.234.66.1: icmp_seq=4 ttl=248 time=17.2 ms

[root@atl ~]# mtr --report --report-cycles=5 104.234.66.1
Start: 2024-01-31T16:44:48-0500
HOST: atl.mirror.knownhost.com    Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 64.74.200.252              0.0%     5    0.5   0.6   0.5   0.7   0.1
  2.|-- 64.74.203.37               0.0%     5    0.6  11.3   0.2  54.6  24.2
  3.|-- satedge2.xe100-0-48.known  0.0%     5    0.4   0.5   0.3   1.3   0.4
  4.|-- core3.bundle-10-bbnet1.ac  0.0%     5    0.9   0.9   0.8   1.1   0.1
  5.|-- ae50.cr2.atl1.us.unitasgl  0.0%     5    1.0   1.0   0.9   1.2   0.1
  6.|-- ae0-49.cr1.atl1.us.unitas 20.0%     5    1.1   1.2   0.9   1.4   0.2
  7.|-- e0-10.cr1.dfw1.us.unitasg 40.0%     5   16.7  16.6  16.6  16.7   0.1
  8.|-- 104.234.66.1               0.0%     5   18.2  17.3  16.9  18.2   0.6
```

**Comment by codyro** [comment]
Are you still experiencing issues with this?
