### ISSUE TITLE
How to check if conversion is Ok after dnf updates fail

### ISSUE THREAD

**Issue by digirave** [AlmaLinux/almalinux-deploy#208]
Hello,

I converted a rhel 8.9 based server to almalinux.
This server has nvidia and cuda drivers installed so kernel updates must be fixed to certain version.
Therefore running
sudo bash almalinux-deploy.sh

resulted in dnf installs/updates failing.
I did not save the error message.

However, after dnf update which excludes the failed dnf rpms, I did a reboot.
Afterwards running almalinux-deploy.sh results in 
package almalinux-release-8.9-1.el8.x86_64 is already installed

I am sure kernel packages are running from prior OS, but since the OS is ABI compatible would it be safe to use as is until I update the kernel(which should be long into the future)?

Thank you.

**Comment by andrewlukoshko** [comment]
Yes our kernels are 100% RHEL compatible so it's fine to use RHEL kernel until next update.
The only issue with RHEL kernels is that Secure Boot mode will not work.
