### ISSUE TITLE
kmail not working in Almalinux 8

### ISSUE THREAD

**Issue by DagNygren** [AlmaLinux/almalinux-deploy#209]
Kmail fails in Almalinux 8 with a symbol lookup error.

$ kmail
kmail: symbol lookup error: /lib64/libKF5TemplateParser.so.5: undefined symbol: _ZNK19KIdentityManagement9Signature7rawTextEPb

**Comment by pastalian** [comment]
I think this is more of an epel issue than almalinux.
kmail on epel8 has been broken for years and in fact the whole kf5 dependency is a mess.
https://bugzilla.redhat.com/show_bug.cgi?id=2118505

I don't expect anyone to fix this anytime soon (or ever).
