### ISSUE TITLE
Convert Centos 7.9 directly to AlmaLinux 8.3

### ISSUE THREAD

**Issue by marcoczen** [AlmaLinux/almalinux-deploy#21]
> In order to convert your EL8 operating system to AlmaLinux do the following...

Guys, 

Is it possible to convert centos 7.9 to almalinux 8.3 directly or must we go centos 8 first and then convert ?

Thanks.

**Comment by andrewlukoshko** [comment]
Hello,

Unfortunately you can't convert centos 7.9 to almalinux 8.3 directly.
Only EL8 OS with the same version can be converted so you should first get centos 8.3.

**Comment by marcoczen** [comment]
> Hello,
> 
> Unfortunately you can't convert centos 7.9 to almalinux 8.3 directly.
> Only EL8 OS with the same version can be converted so you should first get centos 8.3.

Thanks.
So going to 8.0 (as bare minimum) will be needed ?

**Comment by andrewlukoshko** [comment]
You'll need 8.3

**Comment by mekbuk** [comment]
> Hello,
> 
> Unfortunately you can't convert centos 7.9 to almalinux 8.3 directly.
> Only EL8 OS with the same version can be converted so you should first get centos 8.3.

so we just have option the "new server" if want using almalinux from centos 7 ?

**Comment by oranenj** [comment]
@mekbuk the problem is not really converting from CentOS to AL, it's upgrading from 7 to 8, which is not supported with CentOS.

It's probably possible in theory (Red Hat provides some limited support for it), but the exact steps will depend on your setup. If you can figure out how to upgrade from CentOS 7.9 to 8.3, you can then convert ther result.

**Comment by marcoczen** [comment]
Thanks all.
Closed.

**Comment by xiamuguizhi** [comment]
8.1 up > 8.3   and  7.6 > 8.3

1. Check the system version
$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
2. Back up important data (such as /etc, /var, /opt). If centos is installed on a virtual machine, you can use snapshots for backup. Like VMware virtual machines can be snapshot backup, of course, a more luxurious point is to back up the entire virtual machine. It can also back up important program data, such as MySQL, Appache, Nginx, DNS, etc.

Three, run the yum command to upgrade
$ sudo yum clean all
$ sudo yum update
Fourth, restart the system
$ sudo reboot
Five, check the current system version
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
I hope this article can help you successfully upgrade centos 7 to the latest version.
Note: Before upgrading, remember to check that the system is running normally and that the system services have been installed.
