### ISSUE TITLE
loadmap in README.md is not updated.

### ISSUE THREAD

**Issue by kfujina** [AlmaLinux/almalinux-deploy#22]
Hello,

almalinux-deploy already includes follows.

- support migration from Oracle/RHEL 
  edbe0441ded22f2e9b84128d8e14f4a7f02a8f20
- add support for cPanel
  3fb628ecbe7b7402c8dcd4b413a44559634960ca

But loadmap in README.md is not updated.

**Comment by titan-dn** [comment]
updated
