### ISSUE TITLE
From Oracle Linux 8 to Alma Linux 8 : Some packages not removed 

### ISSUE THREAD

**Issue by aaaaadrien** [AlmaLinux/almalinux-deploy#27]
After migration, packages are on the Alma Machine :

oracle-epel-release-el8-1.0-3.el8.x86_64
oracle-logos-httpd-80.5-1.0.6.el8.noarch
oracle-logos-80.5-1.0.6.el8.x86_64

Is it possible to switch with the script : 
-  oracle-epel-release to epel-release
- oracle-logos-httpd to almalinux-logos-httpd

Thanks

**Comment by andrewlukoshko** [comment]
Hello.
Logos switch was already fixed by https://github.com/AlmaLinux/almalinux-deploy/pull/28
oracle-epel-release switch will be added soon

**Comment by andrewlukoshko** [comment]
Fixed by https://github.com/AlmaLinux/almalinux-deploy/pull/42
Closing.
