### ISSUE TITLE
centos-logos-httpd not replaced

### ISSUE THREAD

**Issue by leifhetle** [AlmaLinux/almalinux-deploy#29]
Looks like centos-logos-httpd not replaced by almalinux-deploy.sh

How to reproduce:
Do a minimal install centos 8.3
dnf install httpd
# rpm -qa | grep centos
centos-linux-release-8.3-1.2011.el8.noarch
centos-logos-httpd-80.5-2.el8.noarch
centos-logos-80.5-2.el8.x86_64
centos-gpg-keys-8-2.el8.noarch

# curl -O https://raw.githubusercontent.com/AlmaLinux/almalinux-deploy/master/almalinux-deploy.sh
# bash almalinux-deploy.sh
# reboot
# rpm -qa | grep centos
centos-logos-httpd-80.5-2.el8.noarch

Did the following to fix the issue:
# dnf swap centos-logos-httpd almalinux-logos-httpd

**Comment by andrewlukoshko** [comment]
Hello and thanks for report!
Fixed by https://github.com/AlmaLinux/almalinux-deploy/pull/28
