### ISSUE TITLE
Syntax error in migration script

### ISSUE THREAD

**Issue by PhilipPeake** [AlmaLinux/almalinux-deploy#34]
almalinux-deploy.sh: line 354: syntax error near unexpected token `<'

Line 354:

read -r panel_type panel_version < <(get_panel_info)

**Comment by ezamriy** [comment]
@PhilipPeake, thanks for pointing this out. Although, it is a pretty valid bashism (see https://tldp.org/LDP/abs/html/process-sub.html) I will try to replace it with something more compatible.

What shell are you using (`echo "${SHELL}"`)?

**Comment by PhilipPeake** [comment]
$SHELL -> /bin/bash

# bash --version
GNU bash, version 4.4.19(1)-release (x86_64-redhat-linux-gnu)
Philip

**Comment by PhilipPeake** [comment]
I am wondering if it is some of the ton of garbage dumped into the shell environment that clashes somewhere?
Junk just to make GNOME work the way someone thinks that it should, from what I can see.

Trying tout the simple case:

```
[root@localhost ~]# read -a list < <( od -Ad -w24 -t u2 /dev/urandom )
[root@localhost ~]# echo $list
0000000
[root@localhost ~]# 
```

Looks like that works (well, no syntax error, anyway).

But I also saw this with a previous attempt:

```
[root@localhost ~]# read -a list < <( od -Ad -w24 -t u2 /dev/urandom )
read -a list < <( od -Ad -w24 -t u2 /dev/urandom )
 od -Ad -w24 -t u2 /dev/urandom 
__vte_prompt_command
[root@localhost ~]# echo $list
echo $list
0000000
__vte_prompt_command
[root@localhost ~]#
```

Google tells me that the __vte_prompt_command thing is part of that GNOME garbage.
I think RH (and GNOME) broke bash by stuffing it with all that stuff.

**Comment by donsizemore** [comment]
Just to double-check, are you launching the script with bash?

I hit this error when I ran: `$ sh almalinux-deploy.sh -h`

Then I re-read the example, and ran it with bash:

```
$ bash almalinux-deploy.sh -h
Migrates an EL system to AlmaLinux

Usage: almalinux-deploy.sh [OPTION]...

  -h, --help           show this message and exit
  -v, --version        print version information and exit
```

This is just me testing in a `bento/centos-8.3` Vagrant box. DNF reinstalled 557 packages, and left me with:

`Run dnf distro-sync -y                                                OK`

```
$ cat /etc/redhat-release 
AlmaLinux release 8.3 (Purple Manul)
```

**Comment by PhilipPeake** [comment]
I should have updated this.
I did finally get it to work. 

Same thing, ran it explicitly with bash rather than sh.

I didn’t look, but wonder if there is:

	#!/bin/bash

As the first line of the script. I know a lot of people omit that on Linux these days (which I think is ugly… but then there are a lot of ugly things in Linux)
