### ISSUE TITLE
Setup basic CI pipeline on GitHub Actions

### ISSUE THREAD

**Issue by ezamriy** [AlmaLinux/almalinux-deploy#35]
Despite the fact that we are going to run a full-featured pipeline with all tests in the future, it would be nice to introduce basic PR verification earlier.
There are GitHub actions for both ShellCheck and BATS tests so we can easily enable them for every incoming PR. After enabling it, I can disable direct pushes to the repository and ask all CL/AlmaLinux developers to submit pull requests instead. This will help us to avoid issues like #34.

@soksanichenko could you please take care of it?

**Comment by Sim4n6** [comment]
I can do that as a first contrib PR

**Comment by Sim4n6** [comment]
Done for ShellCheck CI #36

**Comment by ezamriy** [comment]
Thanks a lot for your contribution! I've fixed a failing test in #38 and now everything works perfectly.
