### ISSUE TITLE
Verify almalinux-release-latest.rpm package    ERROR

### ISSUE THREAD

**Issue by suricloud** [AlmaLinux/almalinux-deploy#43]
What to do?

[root@bs ~]# sudo bash almalinux-deploy.sh
Check root privileges                                                 OK
Check Secure Boot disabled                                            OK
Check centos-8.x86_64 is supported                                    OK
Download RPM-GPG-KEY-AlmaLinux                                        OK
Import RPM-GPG-KEY-AlmaLinux to RPM DB                                OK
Download almalinux-release package                                    OK
Verify almalinux-release-latest.rpm package                           ERROR
    /root/.alma.qmHkhX/almalinux-release-latest.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#c21ad6ea)

**Comment by jaboutboul** [comment]
Hello, are you trying to upgrade from CentOS 7 by any chance?

**Comment by suricloud** [comment]
i upgraded from centos 7 to 8 firts and then now alma

**Comment by jaboutboul** [comment]
@suricloud okay so this is not officially supported. You can see a whole thread on it here: #32. Let's just try and get some more information from you to see what the state of the system is like. Can you please send the output of `dnf upgrade`? Thanks.

**Comment by jaboutboul** [comment]
Hi @suricloud Any updates or can we close this issue?

**Comment by Zer0Down** [comment]
I have noticed similar issue if you do not reboot after dnf update. First reboot then rerun almalinux deploy script it will work.

**Comment by kubo6472** [comment]
> I have noticed similar issue if you do not reboot after dnf update. First reboot then rerun almalinux deploy script it will work.

rebooted - no luck

**Comment by aasami** [comment]
I had the same issue. And I didn't upgrade from CentOS7.
`[ldapc@10:56 ~]$ bash almalinux-deploy.sh 
Check root privileges                                                 OK
Download almalinux-release package                                    OK
Verify almalinux-release-latest.rpm package                           ERROR
    /root/.alma.3n0VcG/almalinux-release-latest.rpm: digests SIGNATURES NOT OK
[ldapc@10:59 ~]$ rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
[ldapc@10:59 ~]$ bash almalinux-deploy.sh 
Check root privileges                                                 OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
Your OS is supported                                                  OK`
Importing the keys manually does solve the issue in my case.
