### ISSUE TITLE
Missing systemd symlink after upgrading from Centos 8

### ISSUE THREAD

**Issue by bdpz** [AlmaLinux/almalinux-deploy#51]
First off all, thanks for your work !

After the almalinux-deploy.sh script which was ok and green, I have lost a systemd symlink in /etc/systemd/system/default.target.wants/ 

Maybe all the directory default.target.wants was erased, but I didn't check before reactivating the service so I don't know what happens.

I have reactivated my service with systemctl enable sonarqube.service

My unit :

/etc/systemd/system/sonarqube.service
[Unit]
Description=SonarQube
After=network.target network-online.target mariadb.service
Wants=network-online.target

[Service]
Type=forking
ExecStart=/Local/Sonar/bin/linux-x86-64/sonar.sh start
ExecStop=/Local/Sonar/bin/linux-x86-64/sonar.sh stop
PIDFile=/Local/Sonar/bin/linux-x86-64/SonarQube.pid
User=dev
LimitNOFILE=65536
LimitNPROC=4096

[Install]
WantedBy=default.target

**Comment by bdpz** [comment]
I have reverted my server from a snapshot.

In Centos 8 and Alma Linux "from scratch", default.target is a symlink to /lib/systemd/system/multi-user.target, not a default.target.wants directory.

**Comment by bdpz** [comment]
I have done a new test, and this case seems to be solved.

**Comment by andrewlukoshko** [comment]
Thank you for update!
