### ISSUE TITLE
Suggestion: the script should detect unreachable dnf repo and continue or skip it

### ISSUE THREAD

**Issue by kappa-wingman** [AlmaLinux/almalinux-deploy#52]
I had test the script on a Centos node.
That node had configure yum repo to access a location in /media (DVD disc)
The yum repo is enabled but the DVD is not mounted.
For normal dnf/yum usage it would skip the unmounted dvd location.

When almalinux-deploy is run, it said it had problem with the repo and bailed out.
After I disabled the yum repo (DVD), the script does not resume or continue.

**Comment by andrewlukoshko** [comment]
Hello.
Do you have skip_if_unavailable=1 in repo file for DVD?
Also script is now able to resume migration.

**Comment by kappa-wingman** [comment]
I don't have the parameter skip_if_unavailable=1 for the repo setting.
Ok, it's good to know the script is able to resume migration.
