### ISSUE TITLE
migration script did perform intstall kernel and grub update stage

### ISSUE THREAD

**Issue by niks12** [AlmaLinux/almalinux-deploy#55]
Hi ,
When I tried to execute migration script it didnot perform all steps defined in the script and did not see any error as well. 

It looks like kernel install stage and grub update did not completed .

Here is the steps which I followed to perform migration.

[root@cent2alma linux]# dnf distro-sync -y
Last metadata expiration check: 0:05:52 ago on Tue 25 May 2021 10:32:31 AM UTC.
Error:
 Problem 1: package python3-openstacksdk-0.50.0-1.el8.noarch requires python3-cryptography >= 2.7, but none of the providers can be installed
  - python3-cryptography-3.1-1.el8.x86_64 does not belong to a distupgrade repository
  - problem with installed package python3-openstacksdk-0.50.0-1.el8.noarch
 Problem 2: package python3-oslo-config-2:8.3.3-1.el8.noarch requires python3-importlib-metadata >= 1.7.0, but none of the providers can be installed
  - python3-importlib-metadata-1.7.0-1.el8.noarch does not belong to a distupgrade repository
  - problem with installed package python3-oslo-config-2:8.3.3-1.el8.noarch
 Problem 3: cannot install both python3-importlib-metadata-0.23-1.el8.noarch and python3-importlib-metadata-1.7.0-1.el8.noarch
  - package python3-stevedore-3.2.2-2.el8.noarch requires python3-importlib-metadata >= 1.7.0, but none of the providers can be installed
  - cannot install the best update candidate for package python3-importlib-metadata-1.7.0-1.el8.noarch
  - problem with installed package python3-stevedore-3.2.2-2.el8.noarch
 Problem 4: package python3-openstacksdk-0.50.0-1.el8.noarch requires python3-cryptography >= 2.7, but none of the providers can be installed
  - cannot install both python3-cryptography-2.3-3.el8.x86_64 and python3-cryptography-3.1-1.el8.x86_64
  - package python3-ironicclient-4.4.0-1.el8.noarch requires python3-openstacksdk >= 0.18.0, but none of the providers can be installed
  - cannot install the best update candidate for package python3-cryptography-3.1-1.el8.x86_64
  - problem with installed package python3-ironicclient-4.4.0-1.el8.noarch
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@cent2alma linux]# dnf remove python3-openstacksdk-0.50.0-1.el8.noarch python3-oslo-config-2:8.3.3-1.el8.noarch python3-importlib-metadata-0.23-1.el8.noarch python3-openstacksdk-0.50.0-1.el8.noarch

2) 
1) [root@cent2alma linux]# dnf remove python3-openstacksdk-0.50.0-1.el8.noarch python3-oslo-config-2:8.3.3-1.el8.noarch python3-importlib-metadata-0.23-1.el8.noarch python3-openstacksdk-0.50.0-1.el8.noarch python3-stevedore-3.2.2-2.el8.noarch python3-stevedore-3.2.2-2.el8.noarch

3) [root@cent2alma linux]# dnf distro-sync -y  <<-- now it was successful after downgrading and installation of python3 packages.

4) Current CentOS Version 
[root@cent2alma linux]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

5)
root@cent2alma almalinux-deploy]# bash almalinux-deploy.sh
Check root privileges                                                 OK
Check Secure Boot disabled                                            OK
Check centos-8.x86_64 is supported                                    OK
Download RPM-GPG-KEY-AlmaLinux                                        OK
Import RPM-GPG-KEY-AlmaLinux to RPM DB                                OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
warning: /etc/issue saved as /etc/issue.rpmsave
warning: file /etc/yum.repos.d/CentOS-Linux-Sources.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-PowerTools.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-Plus.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-Media.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-HighAvailability.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-FastTrack.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-Extras.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-Devel.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-Debuginfo.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-ContinuousRelease.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-BaseOS.repo: remove failed: No such file or directory
warning: file /etc/yum.repos.d/CentOS-Linux-AppStream.repo: remove failed: No such file or directory
warning: /etc/dnf/vars/infra saved as /etc/dnf/vars/infra.rpmsave
Remove centos-linux-release package                                   OK
Remove centos-gpg-keys package                                        OK
Remove centos-linux-repos package                                     OK
Verifying...                          ########################################
Preparing...                          ########################################
Updating / installing...
almalinux-release-8.3-4.el8           ########################################
Install almalinux-release package                                     OK
Remove centos-logos package                                           OK
Install almalinux-logos package                                       OK
[root@cent2alma almalinux-deploy]#

**Comment by niks12** [comment]
after running script still it is pointing to centos 8

[root@cent2alma almalinux-deploy]# grubby  --default-title
CentOS Linux (4.18.0-240.22.1.el8_3.x86_64) 8
[root@cent2alma almalinux-deploy]# grubby  --default-kernel
/boot/vmlinuz-4.18.0-240.22.1.el8_3.x86_64
[root@cent2alma almalinux-deploy]#

**Comment by tabapatino** [comment]
Hello,

I  had the same issue, the problem is that you may be on CentOS 8.3 and the script tries to install 7.4.

From the script and error you can finish the installation:

dnf distro-sync -y --allowerasing
dnf -y install kernel
grub2-mkconfig -o /boot/efi/EFI/almalinux/grub.cfg

Reboot and that should be all.

If it can't find the kernel, probably it's blocked at /etc/dnf/dnf.conf

Hope it heps!

**Comment by niks12** [comment]
Hi @tabapatino ,

I managed to migrate from CentOS to Alma . I used steps you provided and in my case there were few conflicting packages so removed those.
