### ISSUE TITLE
8.3 to 8.4 version mismatch

### ISSUE THREAD

**Issue by ashdowntech** [AlmaLinux/almalinux-deploy#56]
When running the upgrade script this afternoon, I get the following error:
  
   Check OS is up to date ERROR
   Please upgrade your OS from 8.3 to 8.4 and retry

However, I'm running the latest available CentOS (CentOS Linux release 8.3.2011). A 'dnf update' confirms that there are no packages pending update and the CentOS repo mirrors are clearly only up to 8.3.

Has the Almalinux release gotten out ahead of the CentOS release?

**Comment by ashdowntech** [comment]
Issue is definitely that Alma 8.4 has been released but there is no matching CentOS 8.4 release. The script will be completely broken for anyone who uses it at the moment. 

Temporary workaround is to find one of the mirrors that haven't updated their almalinux-release-latest-8.x86_64.rpm yet from 8.3 to 8.4 and revise the repo.almalinux lines in the script to reflect the domain of the mirror.

**Comment by andrewlukoshko** [comment]
The script was updated to support migration from 8.3 as well.
Thanks for pointing this out!
