### ISSUE TITLE
Remove check for secure boot now 8.4 is out

### ISSUE THREAD

**Issue by philrandal** [AlmaLinux/almalinux-deploy#58]
There's no longer any need to block upgrades of systems with secure boot enabled as almalinux 8.4 now supports this.

assert_secureboot_disabled() and the call to it from main() can go.

Readme.MD needs updating to say that secure boot is now supported.

I've tested the change and updating a secure-booted system works fine for me

**Comment by andrewlukoshko** [comment]
Hello!
You're right we are working on it.
