### ISSUE TITLE
add support for migration from Rocky Linux

### ISSUE THREAD

**Issue by vrms** [AlmaLinux/almalinux-deploy#86]
I believe Alma and [Rocky Linux](rockylinux.org/) both claim to be the successor of CentOS to some extent (well, it's more then that. Bith claim to be bug compatible with rhel).  So I guess many people will want to figure out which one to choose (and in doing so, watch both projects evolve)

Based on these presumptions it would be just right for the deploy script to work for RockyLinux systems just as if does for CentOS/rhel systems. I furthermore assume it is not really difficult to maintain this even though it goes beyond my own (yet limited) capabilities.

**Comment by andrewlukoshko** [comment]
Hello.
The script already supports migration from Rocky Linux.
Did you run into issues with it?

**Comment by vrms** [comment]
sorry, yes I ran into an error message like "operating system not supported". But (and here the 'sorry' comes into play) that was already a while ago and I did not have the chance to test it once again.

I promise to do so by the end of this week and then report back to you here.

**Comment by andrewlukoshko** [comment]
Thanks! We'll wait for your feedback.

**Comment by vrms** [comment]
I ran the deploy.sh script twice inside an LXD RockyLinux 8.4 Container.

it runs quite a while but still ends with an [error](https://pastebin.com/1BhWrncH) at the end
the [2nd run gets there much quicker](https://pastebin.com/yJf5uHwn) with the same result in the end I believe. 

I can not really say how serious this is but you probably can.

**Comment by andrewlukoshko** [comment]
The script doesn't work well inside a containers no matter LXD or Docker and actually there is no much sense to migrate OS inside a container as the proper way to change OS is just running new container.
Script designed to migrate bare metal servers and VMs.

**Comment by cloudlinuxadmin** [comment]
Andrew,

You are right about docker containers, but not about LXD containers. LXD
are system containers, and as such - they are tritted exactly the same way
as VMs in most use cases. So, making sure we can upgrade inside LXD
containers makes sense

Regards,
Igor Seletskiy |  CEO
CloudLinux OS <https://cloudlinux.com/cloudlinuxos>   |   KernelCare
<https://kernelcare.com>   |   Imunify360 <http://imunify360.com/> |
AlmaLinux <https://almalinux.org>
