### ISSUE TITLE
Migrating a CentOS 8.4 unprivileged LXC/LXD container fails

### ISSUE THREAD

**Issue by kooltux** [AlmaLinux/almalinux-deploy#89]
## Description

Some operations in the script fail when upgrading a CentOS 8.4 unprivileged container running on Proxmox with LXC

Note that it's probably a generic issue that may be reproduced with any container engine (LXC, LXD, Docker and others).

## How to reproduce 

As reproducing my errors would require installing a full Proxmox (hypervisor) instance, I reproduced the issue with a simple LXD running on openSUSE (yes, with lxd installed as a superb rpm and not a crappy snap!). I hope it's more convenient.

Note that the container is not privileged: for example /proc is not writable. This also explains the errors...

You can easily reproduce with the following commands (assuming lxd is already installed on host)
```
$ lxc launch images:centos/8 centos
$ lxc exec centos /bin/bash
[root@centos ~]# curl -O https://raw.githubusercontent.com/AlmaLinux/almalinux-deploy/master/almalinux-deploy.sh
[root@centos ~]# chmod +x almalinux-deploy.sh
[root@centos ~]# ./almalinux-deploy.sh
...
  Reinstalling     : filesystem-3.8-3.el8.x86_64                         10/459
Error unpacking rpm package filesystem-3.8-3.el8.x86_64
error: unpacking of archive failed on file /proc: cpio: chown failed - Inappropriate ioctl for device
error: filesystem-3.8-3.el8.x86_64: install failed
...
  Running scriptlet: systemd-239-45.el8_4.3.x86_64                      458/459 
Couldn't write '0' to 'kernel/yama/ptrace_scope', ignoring: No such file or directory
Couldn't write '|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e' to 'kernel/core_pattern', ignoring: Permission denied
Couldn't write '16' to 'kernel/sysrq', ignoring: Permission denied
Couldn't write '1' to 'kernel/core_uses_pid', ignoring: Permission denied
Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Permission denied
Couldn't write 'fq_codel' to 'net/core/default_qdisc', ignoring: No such file or directory
Couldn't write '1' to 'fs/protected_hardlinks', ignoring: Permission denied
Couldn't write '1' to 'fs/protected_symlinks', ignoring: Permission denied
Couldn't write '81920' to 'net/core/optmem_max', ignoring: No such file or directory
Couldn't write '4194304' to 'kernel/pid_max', ignoring: Permission denied
...
Failed:
  filesystem-3.8-3.el8.x86_64            filesystem-3.8-3.el8.x86_64           Error: Transaction failed


Run dnf distro-sync -y. Exit code: 1                                  ERROR
```

## Error logs

I just pasted the errors above: please see the attached logs for details.
* [almalinux-deploy.debug.log](https://github.com/AlmaLinux/almalinux-deploy/files/7002383/almalinux-deploy.debug.log)
* [almalinux-deploy.log](https://github.com/AlmaLinux/almalinux-deploy/files/7002384/almalinux-deploy.log)

## Analysis and ideas to solve the issue

Basically, we have a few packages that can't be installed/upgraded:
* everything related to kernel packages and boot (grub etc.) should be blacklisted when running in a container (they're not needed)
* some postinstall scripts are failing because /proc may be readonly (unprivileged container): I identified 'filesystem' and systemd causing issues. systemd seems to complain but still it's upgraded (the postinstall script fails gracefully, but everything seems to be in place). The real show-stopper is 'filesystem': it seems that /proc is packaged with some permissions and when rpm extracts the cpio content, it fails to set the permissions. In this case, I don't have any good idea to fix the issue...

Also note that the base image for Centos container comes from [linuxcontainers.org](https://uk.images.linuxcontainers.org/images/centos/8/amd64/default/): it differs from a centos install on bare metal. The image is built with distrobuilder, starting from a centos minimal image, but with some tweaks: the recipe is [here](https://github.com/lxc/lxc-ci/blob/master/images/centos.yaml). It's not so easy to read because all versions/architectures/types (vm or container) are mixed in the same file... In this issue, only the blocks with arch=x86_64, release=8 with type=container are relevant. I made a quick diff between centos.yaml and [almalinux.yaml](https://github.com/lxc/lxc-ci/blob/master/images/almalinux.yaml): they're *very* similar (if you take into account that there's no almalinux 7 and that we don't care about any 8-stream release :rofl: )

What is expected at the end? One way to check if the script almalinux-deploy does the job is to compare a migrated centos container to a vanilla almalinux container: in an ideal world, we would get the same content 😇

There are still some good news: I made another test with a privileged container and it's better, but still with some steps to be skipped. I opened #90 for this.

Hope this helps !

BTW: Thx for your great initiative with AlmaLinux :)

**Comment by andrewlukoshko** [comment]
Thank you for such a great report and investigation!
We are looking into it.
