### ISSUE TITLE
Migrating a CentOS 8.4 privileged LXC/LXD container fails

### ISSUE THREAD

**Issue by kooltux** [AlmaLinux/almalinux-deploy#90]
## Description

Some operations in the script fail when upgrading a CentOS 8.4 *privileged* container running on Proxmox with LXC.

This issue is about the next steps after #89 (failures with unprivileged container): solving #89 requires to solve this one too.

## How to reproduce 

Assuming that lxd is already installed on your host, you can reproduce with the following commands:
```
$ lxc launch images:centos/8 centos -c security.privileged=true -c security.nesting=true
$ lxc exec centos /bin/bash
[root@centos ~]# curl -O https://raw.githubusercontent.com/AlmaLinux/almalinux-deploy/master/almalinux-deploy.sh
[root@centos ~]# chmod +x almalinux-deploy.sh
[root@centos ~]# ./almalinux-deploy.sh
...
Complete!
Run dnf distro-sync -y                                                OK
Restoring of alternatives is done                                     OK
Install AlmaLinux kernel                                              OK
/usr/sbin/grub2-probe: error: failed to get canonical path of `/dev/mapper/vgdata-lxd'.
```

## Error logs

Please see the attached logs for details:
* [almalinux-deploy.debug.log](https://github.com/AlmaLinux/almalinux-deploy/files/7002595/almalinux-deploy.debug.log)
* [almalinux-deploy.log](https://github.com/AlmaLinux/almalinux-deploy/files/7002596/almalinux-deploy.log)

## Analysis and ideas to solve the issue

This time, it's better than #89: all packages are installed successfully, even if we still have some warnings on systemd and if some useless packages are installed (kernel, grub ...). It would be interesting to have a diff of pkg list before/after migration to see what's going on (sorry I had no time for this).

Finally the failure comes from grub and secure boot steps run at the end of the script. I commented the [3 lines at line 827](https://github.com/AlmaLinux/almalinux-deploy/blob/cf3fdbe2cd831d585f754dada2e049949234ae2c/almalinux-deploy.sh#L827) like this:

```
...
    #grub_update
    #reinstall_secure_boot_packages
    #add_efi_boot_record
...
```

And tadaaaa!!! :
```
[root@centos ~]# vi almalinux-deploy.sh 
[root@centos ~]# ./almalinux-deploy.sh 
Check root privileges                                                 OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK

Migration to AlmaLinux is completed
```

Hope this helps !

BTW: Thx for your great initiative with AlmaLinux :)

**Comment by andrewlukoshko** [comment]
Again, thank you.
We are looking into it.
