### ISSUE TITLE
Error When Converting cPanel

### ISSUE THREAD

**Issue by donsony** [AlmaLinux/almalinux-deploy#95]
Error:
 Problem 1: package libstdc++-devel-8.4.1-1.el8.alma.x86_64 requires libstdc++(x86-64) = 8.4.1-1.el8.alma, but none of the providers can be installed
  - cannot install both libstdc++-8.4.1-1.el8.x86_64 and libstdc++-8.4.1-1.el8.alma.x86_64
  - cannot install both libstdc++-8.4.1-1.el8.alma.x86_64 and libstdc++-8.4.1-1.el8.x86_64
  - cannot install the best update candidate for package libstdc++-devel-8.4.1-1.el8.alma.x86_64
  - cannot install the best update candidate for package libstdc++-8.4.1-1.el8.alma.x86_64
 Problem 2: libgcc-8.4.1-1.el8.alma.i686 has inferior architecture
  - package gcc-8.4.1-1.el8.alma.x86_64 requires libgcc >= 8.4.1-1.el8.alma, but none of the providers can be installed
  - cannot install both libgcc-8.4.1-1.el8.x86_64 and libgcc-8.4.1-1.el8.alma.x86_64
  - cannot install both libgcc-8.4.1-1.el8.alma.x86_64 and libgcc-8.4.1-1.el8.x86_64
  - cannot install the best update candidate for package libgcc-8.4.1-1.el8.alma.x86_64
  - cannot install the best update candidate for package gcc-8.4.1-1.el8.alma.x86_64
 Problem 3: problem with installed package gcc-8.4.1-1.el8.alma.x86_64
  - package gcc-8.4.1-1.el8.alma.x86_64 requires libgomp = 8.4.1-1.el8.alma, but none of the providers can be installed
  - libgomp-8.4.1-1.el8.alma.i686 has inferior architecture
  - package gcc-8.4.1-1.el8.x86_64 requires cpp = 8.4.1-1.el8, but none of the providers can be installed
  - cannot install both libgomp-8.4.1-1.el8.x86_64 and libgomp-8.4.1-1.el8.alma.x86_64
  - cannot install both libgomp-8.4.1-1.el8.alma.x86_64 and libgomp-8.4.1-1.el8.x86_64
  - cannot install both cpp-8.4.1-1.el8.x86_64 and cpp-8.4.1-1.el8.alma.x86_64
  - cannot install the best update candidate for package libgomp-8.4.1-1.el8.alma.x86_64
  - cannot install the best update candidate for package cpp-8.4.1-1.el8.alma.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Run dnf distro-sync -y. Exit code: 1                                  ERROR

**Comment by jonathanspw** [comment]
Try getting your system fully updated with "yum upgrade" first.
